services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 7878:7878
    volumes:
      - /opt/stacks/radarr:/config
      - /mnt/nas/data:/data
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.middlewares=internal@file,secure-headers@file"
      - "traefik.http.routers.radarr.tls.certresolver=cloudflare"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

networks:
  traefik:
    external: true
