---
services:
  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /opt/stacks/profilarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      - PROFILARR_PAT=${PROFILARR_PAT}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.profilarr.entrypoints=websecure"
      - "traefik.http.routers.profilarr.middlewares=internal@file,secure-headers@file"
      - "traefik.http.routers.profilarr.tls.certresolver=cloudflare"
      - "traefik.http.routers.profilarr.rule=Host(`profilarr.${DOMAIN}`)"
      - "traefik.http.services.profilarr.loadbalancer.server.port=6868"

networks:
  traefik:
    external: true
