services:
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2:latest
    container_name: nzbhydra2
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 5076:5076
    volumes:
      - /opt/stacks/nzbhydra2:/config
      - /mnt/nas/data/usenet:/data/downloads
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.nzbhydra2.entrypoints=websecure"
      - "traefik.http.routers.nzbhydra2.middlewares=internal@file,secure-headers@file"
      - "traefik.http.routers.nzbhydra2.tls.certresolver=cloudflare"
      - "traefik.http.routers.nzbhydra2.rule=Host(`nzbhydra2.${DOMAIN}`)"
      - "traefik.http.services.nzbhydra2.loadbalancer.server.port=5076"

networks:
  traefik:
    external: true
