---
services:
  copyparty:
    image: copyparty/iv:latest
    container_name: copyparty
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /opt/stacks/copyparty/config:/cfg
      - /mnt/nas/data:/w
    stop_grace_period: 15s
    environment:
      - PUID=1000
      - PGID=1000
      - LD_PRELOAD=/usr/lib/libmimalloc-secure.so.2
      - PYTHONUNBUFFERED=1
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.copyparty.entrypoints=websecure"
      - "traefik.http.routers.copyparty.middlewares=internal@file,secure-headers@file"
      - "traefik.http.routers.copyparty.tls.certresolver=cloudflare"
      - "traefik.http.routers.copyparty.rule=Host(`copyparty.${DOMAIN}`)"
      - "traefik.http.services.copyparty.loadbalancer.server.port=3923"
    healthcheck:
      test:
        - CMD-SHELL
        - wget --spider -q 127.0.0.1:3923/?reset=/._
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s

networks:
  traefik:
    external: true
