---
services:
  fileflows:
    image: revenz/fileflows:stable
    container_name: fileflows
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /opt/stacks/fileflows/data:/app/Data
      - /opt/stacks/fileflows/logs:/app/Logs
      - /opt/stacks/fileflows/tmp:/tmp
      - /mnt/nas/data:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - NVIDIA_VISIBLE_DEVICES=all
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.fileflows.entrypoints=websecure"
      - "traefik.http.routers.fileflows.middlewares=internal@file,secure-headers@file"
      - "traefik.http.routers.fileflows.tls.certresolver=cloudflare"
      - "traefik.http.routers.fileflows.rule=Host(`fileflows.${DOMAIN}`)"
      - "traefik.http.services.fileflows.loadbalancer.server.port=5000"

networks:
  traefik:
    external: true
