services:
  fileflows:
    image: revenz/fileflows:stable
    container_name: fileflows
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 8585:5000
    volumes:
      - /opt/stacks/fileflows/data:/app/Data
      - /opt/stacks/fileflows/logs:/app/Logs
      - /mnt/nas/temp/fileflows:/temp
      - /mnt/nas/data:/media
    environment:
      - TZ=America/Phoenix
      - PUID=99
      - PGID=100
      - NVIDIA_VISIBLE_DEVICES=all
    labels:
      - net.unraid.docker.managed=dockge
      - net.unraid.docker.webui=http://[IP]:[PORT:8585]/
      - net.unraid.docker.icon=https://raw.githubusercontent.com/revenz/FileFlowsUnraid/master/icon.png

networks:
  traefik:
    external: true
