---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    user: "99:100"
    networks:
      - traefik
    volumes:
      - /opt/stacks/sonarr:/config
      - /mnt/nas/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      # - "traefik.http.routers.sonarr.middlewares=sso-forward-auth@file"  # Middleware not defined, uncomment when configured
      - "traefik.http.routers.sonarr.tls.certresolver=cloudflare"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

networks:
  traefik:
    external: true
