services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 10000:8080
    volumes:
      - /opt/stacks/sabnzbd:/config
      - /mnt/nas/data/usenet:/data/usenet
      - /opt/stacks/sabnzbd/scripts:/scripts
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - INSTALL_PACKAGES=clamav-daemon
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.sabnzbd.entrypoints=websecure"
      - "traefik.http.routers.sabnzbd.middlewares=internal@file,secure-headers@file"
      - "traefik.http.routers.sabnzbd.tls.certresolver=cloudflare"
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${DOMAIN}`)"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true
