---
services:
  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /opt/stacks/huntarr:/config
    environment:
      - BASE_URL=
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.huntarr.entrypoints=websecure"
      - "traefik.http.routers.huntarr.middlewares=internal@file,secure-headers@file"
      - "traefik.http.routers.huntarr.tls.certresolver=cloudflare"
      - "traefik.http.routers.huntarr.rule=Host(`huntarr.${DOMAIN}`)"
      - "traefik.http.services.huntarr.loadbalancer.server.port=9705"

networks:
  traefik:
    external: true
