services:
  whisparr:
    image: ghcr.io/hotio/whisparr:v3
    container_name: whisparr
    restart: unless-stopped
    hostname: whisparr.internal
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - traefik
    ports:
      - 6969:6969
    volumes:
      - /opt/stacks/whisparr:/config
      - /mnt/nas/data:/data
    environment:
      - PUID=99
      - PGID=100
      - UMASK=0002
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
      - VPN_ENABLED=false
      - VPN_CONF=wg0
      - VPN_PROVIDER=generic
      - VPN_AUTO_PORT_FORWARD=false
      - VPN_KEEP_LOCAL_DNS=false
      - VPN_FIREWALL_TYPE=auto
      - VPN_PIA_DIP_TOKEN=no
      - VPN_PIA_PORT_FORWARD_PERSIST=false
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.whisparr.entrypoints=websecure"
      - "traefik.http.routers.whisparr.middlewares=internal@file,secure-headers@file"
      - "traefik.http.routers.whisparr.tls.certresolver=cloudflare"
      - "traefik.http.routers.whisparr.rule=Host(`whisparr.${DOMAIN}`)"
      - "traefik.http.services.whisparr.loadbalancer.server.port=6969"

networks:
  traefik:
    external: true
